# Путь до файла сценария
locustfile = ./scenarios/grpc/gateway/existing_user_get_operations/scenario.py

# Общее количество виртуальных пользователей
# Выбрано 250 - высокая нагрузка для очень частого сценария
users = 250

# Скорость запуска пользователей (пользователей/секунду)
spawn-rate = 25

# Продолжительность теста (4 минуты)
run-time = 4m

# Запуск без веб-интерфейса
headless = true

# Путь для сохранения HTML-отчёта
html = ./scenarios/grpc/gateway/existing_user_get_operations/report.html

# Уровень логирования
loglevel = INFO

# Хост (фиктивное значение, так как клиент использует свой канал)
host = localhost