# Путь до файла сценария
locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py

# Общее количество виртуальных пользователей
# Выбрано 200 - высокая, но не пиковая нагрузка для частого сценария
users = 200

# Скорость запуска пользователей (пользователей/секунду)
spawn-rate = 20

# Продолжительность теста (4 минуты)
run-time = 4m

# Запуск без веб-интерфейса
headless = true

# Путь для сохранения HTML-отчёта
html = ./scenarios/http/gateway/existing_user_get_operations/report.html

# Уровень логирования
loglevel = INFO

# Хост (фиктивное значение, так как клиент использует свой base_url)
host = localhost