# Путь до файла сценария
locustfile = ./scenarios/grpc/gateway/new_user_issue_physical_card/scenario.py

# Общее количество виртуальных пользователей
# Выбрано 80 - умеренная нагрузка для непикового сценария (gRPC эффективнее HTTP)
users = 80

# Скорость запуска пользователей (пользователей/секунду)
# Плавный запуск для равномерной нагрузки
spawn-rate = 8

# Продолжительность теста (4 минуты)
run-time = 4m

# Запуск без веб-интерфейса
headless = true

# Путь для сохранения HTML-отчёта
html = ./scenarios/grpc/gateway/new_user_issue_physical_card/report.html

# Уровень логирования
loglevel = INFO

# Хост (фиктивное значение, так как клиент использует свой канал)
host = localhost

csv = locust_grpc_gateway_new_user_issue_physical_card
csv-full-history = true