# Путь до файла сценария
locustfile = ./scenarios/grpc/gateway/existing_user_issue_virtual_card/scenario.py

# Общее количество виртуальных пользователей
# Выбрано 200 - высокая нагрузка для важного сценария
users = 200

# Скорость запуска пользователей (пользователей/секунду)
spawn-rate = 20

# Продолжительность теста (4 минуты)
run-time = 4m

# Запуск без веб-интерфейса
headless = true

# Путь для сохранения HTML-отчёта
html = ./scenarios/grpc/gateway/existing_user_issue_virtual_card/report.html

# Уровень логирования
loglevel = INFO

# Хост (фиктивное значение, так как клиент использует свой канал)
host = localhost