# Путь до файла сценария
locustfile = ./scenarios/http/gateway/existing_user_issue_virtual_card/scenario.py

# Общее количество виртуальных пользователей
# Выбрано 150 - высокая нагрузка для важного, но не самого частого сценария
users = 150

# Скорость запуска пользователей (пользователей/секунду)
spawn-rate = 15

# Продолжительность теста (4 минуты)
run-time = 4m

# Запуск без веб-интерфейса
headless = true

# Путь для сохранения HTML-отчёта
html = ./scenarios/http/gateway/existing_user_issue_virtual_card/report.html

# Уровень логирования
loglevel = INFO

# Хост (фиктивное значение, так как клиент использует свой base_url)
host = localhost